### ISSUE TITLE
nomad_group_name must be included in groups

### ISSUE THREAD

**Issue by luluff** [ansible-community/ansible-nomad#105]
### `nomad_group_name`
- Ansible group that contains all cluster nodes
- Default value: **nomad_instances**

how should i use this `nomad_group_name`?  if i use defalut value ,i get some error :nomad_group_name must be included in groups

**Comment by kiwimato** [comment]
For anyone else hitting this: the issue in my case was to set the group name in inventory file exactly like specified in `examples/vagrant_hosts` file:
`[nomad_instances]`
