### ISSUE TITLE
Approaching Plugin settings stanza

### ISSUE THREAD

**Issue by lanefu** [ansible-community/ansible-nomad#106]
* will existing nomad_options parameter work?

* should we define plugin options as seperate blocks and render separate config file?

https://www.nomadproject.io/docs/configuration/plugin

**Comment by beechesII** [comment]
Hi @lanefu ,
seems the Issue can be closed. https://github.com/ansible-community/ansible-nomad/pull/111 include the possibility to configure nomad plugin stanza.

**Comment by lanefu** [comment]
resolved by #111
