### ISSUE TITLE
Compatibility with the version 1.0.0

### ISSUE THREAD

**Issue by msirovy** [ansible-community/ansible-nomad#114]
I have a fix for this, could you allow me to send it as a new branch?

This is how does the fix look like:

```diff
+{% if nomad_version | replace(".", "0000") | int >= 10000000000 %}
+    # Deprecated in 1.0.0
+    backwards_compatible_metrics = "{{ nomad_telemetry_backwards_compatible_metrics | default(false) | bool | lower }}"
+    disable_tagged_metrics = "{{ nomad_telemetry_disable_tagged_metrics | default(false) | bool | lower }}"
+{% endif %}
```

**Comment by rndmh3ro** [comment]
Hey @msirovy,

you might want to check out https://gist.github.com/Chaser324/ce0505fbed06b947d962 how to create a fork of this repo and create a PR.

As to the content: You can compare versions in Ansible with `version_compare`: https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#comparing-versions

**Comment by bbaassssiiee** [comment]
In 2.5 version_compare was renamed to version

**Comment by lanefu** [comment]
Looks to be resolved by https://github.com/ansible-community/ansible-nomad/pull/115

but... sounds like a revision of how `version_compare` is done should be revised?
