### ISSUE TITLE
Ubuntu 18.04 and 20.04 support regression

### ISSUE THREAD

**Issue by sas1024** [ansible-community/ansible-nomad#186]
Hello!
This role fails to works on all servers with Ubuntu 18.04 and Ubuntu 20.04. It's fails with following error:
```
FAILED! => {"assertion": "ansible_distribution_version is version(version_to_compare, '>')", "changed": false, "evaluated_to": false, "msg": "20.04 is not supported for this role"}
```

As I see, this regression starts from this commit: 82c3714bb7c1f9a9cc74866fdcaef96c61d748b1
There are changed `os_supported_matrix` in `default.yml`.

If I change `Ubuntu min_version` value to `16.04` in `os_supported_matrix`, then ansible role will works on Ubuntu 18.04 and Ubuntu 22.04.

**Comment by rndmh3ro** [comment]
16.04 and 18.04 are out of support (see https://hub.docker.com/_/ubuntu and https://endoflife.date/ubuntu).

But 20.04 not being supported is indeed a regression.
We should probably change [this line](https://github.com/ansible-community/ansible-nomad/commit/82c3714bb7c1f9a9cc74866fdcaef96c61d748b1#diff-ac9775f584b981e0a7d9cf06283477a299684b77eebb3d635b1c206b394f6038L34) to:

```
- ansible_distribution_version is version(version_to_compare, '>=')
```
