### ISSUE TITLE
Enhancing syslog logging.

### ISSUE THREAD

**Issue by ykhemani** [ansible-community/ansible-nomad#33]
Hello!

Similar to what we did for logging in the [ansible-consul](https://github.com/brianshumate/ansible-consul/issues/144) role, shall we enhance syslog logging for ansible-nomad?

Ownership of {{ nomad_log_dir }} would be set to syslog:adm to enable rsyslogd to write to that directory.

We would like to be able to define syslog facility used for logging messages. Suggest we define the variable nomad_syslog_facility for this purpose.

Also, in order to have rsyslogd write nomad logs to {{ consul_log_path }}, we need a corresponding rule to the syslog facility. Suggest that this happens via the /etc/rsyslog.d/00-nomad.conf.

I will submit a PR for your review.

Please let me know if you have any questions.

Thanks!
-yash

**Comment by brianshumate** [comment]
Hey there yash! Sorry for taking so long to get back to you.

This would be a fine enhancement, thanks!

**Comment by lanefu** [comment]
closing old issue
