### ISSUE TITLE
Add telemetry support

### ISSUE THREAD

**Issue by bcochofel** [ansible-community/ansible-nomad#59]
Hi Brian, first of all, amazing role, thanks for this.

I'm wondering if you could add support for telemetry also? This way we can also get metrics from Nomad nodes.

Thanks,
Bruno

**Comment by brianshumate** [comment]
Hi Bruno!

Thanks for the kind words. Seems like a good feature to have. I will try to implement it soon.

**Comment by lanefu** [comment]
added in #88
