### ISSUE TITLE
Nomad job bind network interface

### ISSUE THREAD

**Issue by bcochofel** [ansible-community/ansible-nomad#60]
Hi,

I have used your ansible role to deploy nomad on Virtualbox (my Vagrantfile).
On the VB I have each server with two network interfaces:

- NAT: eth0
- host-only: eth1

I have configured the "nomad_iface" to "eth1" but my jobs get bind only on eth0.

I also have "nomad_bind_address" => "0.0.0.0", because without this my server only listens on loopback device.

Do I need to do anything else?

Thanks,
Bruno

**Comment by gentoo9ball** [comment]
Also trying to figure this out. Thanks!

**Comment by lanefu** [comment]
@bcochofel happy 1 year anniversary to the issue...

I'm looking at how I've dealt with this...

I believe you want to set the `bind_address` to 0.0.0.0 as you've done, and then set your `nomad_advertise_address` to the IP of your preferred interface.. in this case, eth1.

Additionally.. not sure if this is needed. you could try

```
nomad_config_custom:
  client:
    network_interface: "eth1"
```

**Comment by lanefu** [comment]
closing feel free to comment and I'll reopen
