### ISSUE TITLE
Add rpc_upgrade_mode for TLS

### ISSUE THREAD

**Issue by ducminhle** [ansible-community/ansible-nomad#81]
When we upgrade from no TLS to TLS, we need the parameter `"rpc_upgrade_mode" = true` in TLS config.
https://learn.hashicorp.com/nomad/transport-security/enable-tls#rpc-upgrade-mode-for-nomad-servers
https://nomadproject.io/docs/configuration/tls/

**Comment by lanefu** [comment]
Merged in #80 Thanks!
