### ISSUE TITLE
ensure unzip is installed on localhost

### ISSUE THREAD

**Issue by pxsloot** [ansible-community/ansible-nomad#89]
The download and unzip steps of the installation of nomad are delegated to localhost and will fail when `unzip` is not available.
This role fails to run from the container version of `ansible/awx`. 

Workaround was to install unzip in the ansible/awx container from the playbook, before the call to this role.

A patch for ansible-nomad would be non-trivial, because the ability to install `unzip` on localhost from a package is not guaranteed. Perhaps the dependency for `unzip` on localhost could be mentioned in the `README.md`

**Comment by lanefu** [comment]
Hi @pxsloot I opted to just update the readme since the role is just using the ansible unarchive module, and unzip is a dependency for unarchive module.   The role doesn't do much as far as modifying the ansible control node.
