### ISSUE TITLE
Convert travis-ci to GitHub workflow

### ISSUE THREAD

**Issue by lanefu** [ansible-community/ansible-nomad#91]
need ci-testing like ansible-consul

**Comment by lanefu** [comment]
WIP #95 taming ansible-molecule

**Comment by MonolithProjects** [comment]
Did some work here. Plz check the https://github.com/ansible-community/ansible-nomad/pull/112

**Comment by lanefu** [comment]
@MonolithProjects oh thank you so much!

**Comment by lanefu** [comment]
merged #112

**Comment by beechesII** [comment]
molecule tests fixed by PR #95
