### ISSUE TITLE
Upgrade 0.12

### ISSUE THREAD

**Issue by lanefu** [ansible-community/ansible-nomad#97]
Upgrade 0.12,  add new configuration vars as needed

**Comment by adawalli** [comment]
@lanefu - I don't mind taking this on

I just looked at the history on the agent CONFIG page and I dont see any changes for quite a bit : https://github.com/hashicorp/nomad/blob/v0.12.0/website/pages/docs/configuration/index.mdx

Do you have a better way to check for config changes?

**Comment by lanefu** [comment]
> @lanefu - I don't mind taking this on
> 
> I just looked at the history on the agent CONFIG page and I dont see any changes for quite a bit : https://github.com/hashicorp/nomad/blob/v0.12.0/website/pages/docs/configuration/index.mdx
> 
> Do you have a better way to check for config changes?

nope seems like a great approach
